#!/usr/bin/env python

from sys import argv, path
from pathlib import Path
from os import getcwd
from os.path import splitext
from importlib import import_module
from thunderlight.server import Server
from thunderlight.main import gimme


def help():
    print('\nLaunch the thunderlight server.\n\nUsage: thunderlight [app] [port]\n\nArguments:\n    app (optional) the module and object to load.\n    port (the port to listen.)\n\nExamples:\n    (1) thunderlight app 5000\n    (2) thunderlight app:app\n    (3) thunderlight')


def launch(args: list[str]):
    if len(args) == 0:
        args.append('app')
    if len(args) == 1:
        args.append('5000')
    if ':' in args[0]:
        file = args[0].split(':')[0]
        obj: str | None = args[0].split(':')[1]
    else:
        file = args[0]
        obj = None
    dest = Path(getcwd())
    app_file = dest / args[0]
    path.append(str(dest))
    result = import_module(splitext(app_file.name)[0], str(dest)).__dict__
    if obj:
        app = result[obj]
        print("THIS")
    else:
        app = gimme()
        print("THAT")
    port = int(args[1])
    server = Server(app, port)
    #server.listen()


if __name__ == '__main__':
    args = argv[1:]
    if '--help' in args or '-h' in args:
        help()
    else:
        launch(args)
